name: docker build
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build and publish docker image to github
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${secrets.MY_TOKEN}
          image-name: my_library__image
          dockerfile: Dockerfile
          # build-context: storybook-static

      - name: github pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
